config/routes.rb
Rails.application.routes.draw do


  devise_for :users, controllers: {registrations: 'registrations', omniauth_callbacks: 'omniauth'}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get 'users/famous_user'=> 'users#famous_user'

  resources :users do
    resources :post_comments
    resources :posts

    resources :movie_comments
    resources :movies
  end

  resources :post_comments
  get 'posts'=> 'posts#all'

  root to: "application#home"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord

    belongs_to :user
    has_many :post_comments , dependent: :delete_all
    has_many :users_who_commented, through: :post_comments, source: :user

    validates :content, presence: :true


end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :username, presence: :true
  validates :body, presence: :true


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:github, :google_oauth2]

  has_many :posts
  has_many :post_comments ,:dependent => :destroy
  has_many :commented_posts, through: :post_comments, source: :post



  scope :famous_users, -> {where("view > ?", 50)}



  def self.in_age(age)
      where(:age => age)
  end


  def self.create_from_provider_data(provider_data)
    where(provider: provider_data.provider, uid: provider_data.uid).first_or_create do |user|
      user.email = provider_data.info.email
      user.password = Devise.friendly_token[0, 20]
    end
  end





end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    add_flash_types :info, :error, :warning
end

app/controllers/omniauth_controller.rb
class OmniauthController < ApplicationController
    def github
        @user=User.create_from_provider_data(request.env['omniauth.auth'])
        if @user.persisted?
            sign_in_and_redirect @user

        else
            flash[:error] = 'There was a problem signing you in through Github. Please register or try signing in later.'
            redirect_to new_user_registration_url
        end
    end

    def google_oauth2
        @user=User.create_from_provider_data(request.env['omniauth.auth'])
        if @user.persisted?
            sign_in_and_redirect @user

        else
            flash[:error] = 'There was a problem signing you in through Google. Please register or try signing in later.'
            redirect_to new_user_registration_url
        end
    end

    def failure
        flash[:error]= 'There was a problem signing you in. Please register or try signing in later '
        redirect_to new_user_registration_url
    end

end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController
  def index
  end

  def new
  end



  def create


    @post=Post.find(params[:post_comment][:post_id])

    @post_comment= current_user.post_comments.build(post_comment_params)

    if @post_comment.valid?

      @post_comment.save
      @user=@post.user

      redirect_to user_post_comment_path(current_user, @post_comment)
    else
      flash[:error]="Display Name and Your Comment can't be blank"
      redirect_to user_post_path(current_user,@post)
    end
  end

  def show

    # @post_owner= User.find(params[:user_id])


    @comment= PostComment.find(params[:id])
    @commenter= @comment.user
    @post=@comment.post
    @post_owner=@post.user


  end

  def edit

    @comment= PostComment.find_by_id(params[:id])
    @comment_owner= @comment.user

  end

  def update

    @comment= PostComment.find(params[:id])

    @updated_username=params[:post_comment][:username]
    @updated_body=params[:post_comment][:body]
    if @comment.update(:username=> @updated_username, :body=>@updated_body)


      redirect_to user_posts_path(@comment.user)
    else
      render :edit
    end
  end

  def destroy

    @comment=PostComment.find(params[:id])
    @comment_owner=@comment.user
    @comment_post=@comment.post
    @comment.delete
    redirect_to user_posts_path(@comment_owner,@comment_post)

  end

  private
  def post_comment_params
    params.require(:post_comment).permit(:username, :body, :post_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index

    @user=User.find(params[:user_id])
    @posts=@user.posts.all


  end

  def new
    @user=User.find(params[:user_id])
    @post=@user.posts.build

  end

  def create

    @user=User.find(params[:user_id])
    @post=@user.posts.build(post_params)
    if @post.save
      redirect_to user_post_path(@user, @post)
    else
      render :new
    end
  end

  def show

    @post=Post.find(params[:id])
    if User.find(params[:user_id])== @post.user
      @user= User.find(params[:user_id])
    else
      @user=@post.user

    end

    @user_posts=@user.posts
    @post_owner=@user
    @post_comments=@post.post_comments

  end

  def edit
    @post=Post.find(params[:id])
    @user=User.find(params[:user_id])
  end

  def update
    @user=User.find(params[:user_id])
    @post=Post.find(params[:id])
    if @post.update(post_params)
      redirect_to user_post_path(@user,@post)
    else
      render :edit
    end
  end

  def destroy

    @post=Post.find(params[:id])
    @user=User.find(params[:user_id])
    @post.destroy

    redirect_to user_posts_path(@user)
  end

  def all
    @all_posts=Post.all
    @all_users=User.all
    @all_users_count=User.all.count
    render :all
  end

  private
  def post_params
    params.require(:post).permit([:content])
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

    private

        def sign_up_params
            params.require(:user).permit(:email, :password, :password_confirmation, :name, :age)
        end

        def account_update_params
            params.require(:user).permit(:email, :password, :password_confirmation, :current_password, :name, :age, :views)
        end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users=User.all
  end

  def new
  end

  def show

    @user=User.find(params[:id])
    @users=User.all
    @profile_owner=@user
    @user_posts=@user.posts

    @views= @user.view

    if @user != current_user
      @updated_views=@views+1
      @user.update(:view=>@updated_views)
    else
      @views=@views
    end

  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end

  def famous_user
    @famous_user_ar_relation = User.famous_users
    @famous_user=User.find_by_id(@famous_user_ar_relation.first.id)
    @views=@famous_user.view

  end

  private

  def user_params

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/omniauth_helper.rb
module OmniauthHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/home.erb
<h1>Welcome home <%= current_user ? current_user.name : nil %>!</h1>

app/views/layouts/_messages.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/_nav.erb
<div class="container">
    <% if user_signed_in?%>

         <br /> <br /> <br /> <br />
        <p id="light_green"><%= link_to "My Profile", user_path(current_user) %>
        &nbsp;&nbsp;&nbsp;<%= link_to "My posts", user_posts_path(current_user) %>
        &nbsp;&nbsp;&nbsp;<%= link_to "All Users", users_path %>
        &nbsp;&nbsp;&nbsp;<%= link_to "All Posts", posts_path %>
        &nbsp;&nbsp;&nbsp;<%= link_to "Edit account info", edit_user_registration_path %>
        &nbsp;&nbsp;&nbsp;<%= link_to "Sign out", destroy_user_session_path , method: :delete %>
        &nbsp;&nbsp;&nbsp;current user:<%= link_to current_user.name , user_path(current_user) %></p>
        <br />

    <% else %>
         <br /> <br /> <br />
        <li><%= link_to "Sign in ", new_user_session_path  %></li>
        <li><%= link_to "Sign up", new_user_registration_path %></li>
        <li><%= link_to "Sign in with Github", user_github_omniauth_authorize_path %></li>
        <li><%= link_to "Sign in with Google", user_google_oauth2_omniauth_authorize_path %></li>
    <% end  %>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProducersBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>



  <body>

    <style>




       .post {
        background-color: greenyellow;
        color: black;
        margin: 2px;
        padding: 20px;
        display: inline-block

      }

      .comment {
        background-color: darkgrey;
        color: white;
        margin: 2px;
        padding: 20px;
        display: inline-block

      }

      .post-comment {
        background-color: cyan;
        color: black;
        margin: 2px;
        padding: 20px;
        display: inline-block

      }

      .wide-text-area{
        width:100%;
      }

      #lime { color: #2EEC08; }

      #cyan_blue { color: #08ECE1 }

      #blue { color: #088BEC }

      #light_green { color: #30FB03 }

      #brown { color: #FC7F03 }

      #red { color: #FC0303 }

      .field_with_errors {
          @extend .control-group;
          @extend .error;

          display: inline-block;
      }

    </style>


    <br />
    <br />
    <br />
    <br />



    <body>
        <% flash.keys.each do |type| %>
          <div data-alert class="flash <%= type %> alert-box radius">

            <a href="." class="close">&times;</a>
          </div>
        <% end %>
    <script>
      function startTime() {
        var today = new Date();
        var h = today.getHours();
        var m = today.getMinutes();
        var s = today.getSeconds();
        m = checkTime(m);
        s = checkTime(s);
        document.getElementById('txt').innerHTML =
        h + ":" + m + ":" + s;
        var t = setTimeout(startTime, 500);
      }
      function checkTime(i) {
        if (i < 10) {i = "0" + i};  // add zero in front of numbers < 10
        return i;
      }
  </script>
    <div class="wrapper">


        <div class="container">
          <p><%= render 'layouts/messages' %><p>

          <%= yield %>

        </div>
          </body>
          <footer>
            <%= render 'layouts/nav' %>
        <div class="container">
            <small>&copy; 2020 <strong>Producer-blog</strong></small>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <%=Time.parse((Time.new-100).to_s).strftime("%A, %b %d")%> Pacific Daylight Time<br>
            <body onload="startTime()"><br>
            Time : <div id="txt" ></div>

          </div>
    </div>
  </footer>
</html>

app/views/post_comments/create.html.erb
<h1>PostComments#create</h1>
<p>Find me in app/views/post_comments/create.html.erb</p>

app/views/post_comments/destroy.html.erb
<h1>PostComments#destroy</h1>
<p>Find me in app/views/post_comments/destroy.html.erb</p>

app/views/post_comments/edit.html.erb
<h1>Edit post</h1>

<%= form_for :post_comment, url: user_post_comment_path(@comment_owner,@comment) , method: :patch do |f| %>

    <p>
        <%= f.label :username, "Your name" %>
        <%= f.text_field :username %>
    </p>

    <p>
        <%= f.label :body, "Your comment" %>
        <%= f.text_area :body, class: "wide-text-area"  %>
    </p>


    <p>
        <%= f.submit  ({:class => 'btn btn-primary'})%>
    </p>
<% end %>

app/views/post_comments/index.html.erb
<h1>PostComments#index</h1>
<p>Find me in app/views/post_comments/index.html.erb</p>

app/views/post_comments/new.html.erb
<h1>Username can't be blank</h1>
<h1>Body can't be blank</h1>

app/views/post_comments/show.html.erb
<h1>Post Comment</h1>

<div class="post-comment">
   <h2> <%= @comment.body %>&nbsp;&nbsp;&nbsp;

   <% if @commenter==current_user %>
        <%= link_to "Edit post", edit_user_post_comment_path(@comment),:class => 'btn btn-primary'  %>
        <%= link_to "Delete", user_post_comment_path(@comment.user,@comment), method: :delete,
            data: {confirm: 'Are you 200% sure?'},:class => 'btn btn-danger' %></h2>
    <% end  %>
</div>

app/views/post_comments/update.html.erb
<h1>PostComments#update</h1>
<p>Find me in app/views/post_comments/update.html.erb</p>

app/views/posts/all.erb
<h1>Here are all existing posts from Users</h1>



<% @all_users.each do |user| %>
    <% if user.name %>
        <p><%= link_to user.name.upcase, user_path(user) %>'s posts count : <%= user.posts.count %></p>
        <% user.posts.each do |post| %>
            <ul>
                <li><%= link_to post.content, user_post_path(user,post)  %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%=post.created_at.to_datetime.strftime("%A, %b %d at %I:%M%p")%>
 </li>
            </ul>

        <% end %>
    <% else  %>
        <p><%= link_to user.email.upcase, user_path(user) %>'s posts count : <%= user.posts.count %></p>
        <% user.posts.each do |post| %>
            <ul>
                <li><%= link_to post.content, user_post_path(user,post) %></li>
            </ul>

        <% end %>
    <% end %>

<% end  %>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= form_for :post, url: user_post_path(@user, @post), method: :patch do |f| %>
    <p>
        <%= f.label :content %>
        <%= f.text_field :content %>
    </p>

    <p>
    <%= f.submit "Update", {:class => 'btn btn-primary'}%>
    </p>
<% end  %>

app/views/posts/index.html.erb
<h1>Total posts: <%= @posts.count %></h1>

<% if @posts %>

    <% @posts.each do |post| %>
        <ul>
        <li><%= link_to post.content, user_post_path(@user, post) %></li>
        </ul>
    <% end  %>

<% end  %>

<h4><%= link_to "Create Post", new_user_post_path(current_user),:class => 'btn btn-primary' %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

</h4>

app/views/posts/new.html.erb
<h1>Create Post</h1>

<% if @post.errors.any? %>
   <p id="red"><%= @post.errors.full_messages.to_sentence %></p>

<% end  %>


<%= form_for ([@user, @post]) do |f| %>


    <p>
        <%= f.label :content %>
        <%= f.text_field :content %>
    </p>

    <%= f.submit "Create", {:class => 'btn btn-primary'}%>
<% end  %>

app/views/posts/show.html.erb
<div class="comment">
    <h1><%= @post.content %></h1>
</div>
<h6> <%=@post.created_at.to_datetime.strftime("%A, %b %d at %I:%M%p")%>
 by <%= @post_owner.name %></h6> <br />

<h3>Comments</h3>

<% if @post.post_comments.count == 0 %>
    <h5>There are no comments for this post yet. Wana be first? </h5>

<% else %>

    <% @post.post_comments.each do |comment| %>
        <div class="post-comment">
            <h5><%= link_to comment.body, user_post_comment_path(comment.user,comment) %>-------------
            <%= comment.username %></h5>
        </div>
        <br />
    <% end %>


<% end %>


<br/>




<% if @post_owner == current_user %>

    <%= link_to "Edit", edit_user_post_path(@user,@post),:class => 'btn btn-primary' %>&nbsp;&nbsp;&nbsp;

    <%= link_to "Delete", user_post_path(@user, @post), method: :delete, data: {confirm: 'Are you 200% sure?'},:class => 'btn btn-danger' %> <br /><br />





<% end  %>


<br/>

<h2 id="red"> <%= flash[:error] %> </h2>

<%= form_for @post.post_comments.build do |f| %>
    <%= f.hidden_field :post_id, value: @post.id %>

    <p>
        <%= f.label :username, "Display Name" %>
        <%= f.text_field :username %>
    </p>

    <p>
        <%= f.label :body, "Your comment" %>
        <%= f.text_area :body, class: "wide-text-area"  %>
    </p>


    <%= f.submit  ({:class => 'btn btn-primary'})%>

<% end %>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/famous_user.erb
 <h3>Famous User/Users around here: </h3><br /><br /><br />
 <h3 id="lime"><%= link_to @famous_user.name, user_path(@famous_user) %> with the profile view of <%= @views %> </h3>
 <h1 id="brown">Congrats to Ben!!!!</h1>

app/views/users/index.html.erb
<h1>Existing Users List</h1><br /><br >
<% @users.each do |user| %>

    <%= link_to user.name, user_path(user) %>&nbsp;&nbsp;&nbsp;

<% end %>

<br /><br />
<h5>Are you the famous user around here? Click <%= link_to "here", users_famous_user_path %> to check</h5>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<% if current_user != @profile_owner %>

    <div class="container">
        <h5 id="lime">Profile Views: <%= @profile_owner.view %></h5>
        <h1 id="cyan_blue">Welcome <%= current_user.name %> to <%= @profile_owner.name %>'s profile</h1>

        <% if @profile_owner.view > 30 %>
            <h4>Did you know <%=@profile_owner.name %> is pretty popular out here!</h4>
        <% end  %>

        <p>
        <% if @profile_owner.commented_posts.count == 0 %>
            <%= @profile_owner.name %> doesnot have any commented posts.<p>

        <% else %>

            <% @profile_owner.commented_posts.distinct.each do |post| %>
                <ul>
                    <h5><li> <%= link_to post.content, user_post_path(@profile_owner,post) %></li></h5>
                </ul>
            <% end  %>

        <% end %>


        <% if @profile_owner.posts.count >= 1 %>

            Here are posts <%= @profile_owner.name %> created:
            <%@profile_owner.posts.each do |post| %>
            <ul>
                <li><h5><%= link_to post.content, user_post_path(@profile_owner,post) %></h5></li>
            </ul>
            <% end  %>

        <% else %>
            <h5><%= @profile_owner.name %> doesnot have a post yet</h5>
        <% end  %>



         </h3>

    </div>

<% else %>



    <div class="container">
        <h5>Profile Views: <%= @current_user.view %></h5>
        <h1>Welcome <%= current_user.email %></h1>
        <% if current_user.view > 30 %>
            <h4>Did you know <%=current_user.name %>, you are a big deal out here.Congrats!</h4>
        <% end  %>

        <h6>Posts that you commented on : </h6><p>
        <% @profile_owner.commented_posts.distinct.each do |post| %>
            <ul>
                <li><%= link_to post.content, user_post_path(@profile_owner, post)   %></li>
            </ul>
        <% end  %>

        <% if !current_user.posts.nil? %>
            <h6>Posts that you created<h6>
            <%current_user.posts.each do |post| %>
                <ul>
                    <li><h5><%= link_to post.content, user_post_path(current_user,post) %></h5></li>
                </ul>
            <% end  %>

        <% else %>
            <h5>You currently don't have any post yet </h5>

        <% end %>

        <br />
    </div>


<% end  %>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>